/*
 * Build information - auto-generated by scripts/generate_buildinfo.py
 * Generated: 2025-12-21T05:58:14Z
 */

#include "buildinfo.h"

namespace BuildInfo {

const char* version = "0.0.0-dev";
const char* gitSha = "6581f3164e4098166ab5015fb46797bd36c1df5d";
const char* gitShortSha = "6581f31";
const char* gitBranch = "master";
const char* buildDate = "2025-12-21T05:58:14Z";
const bool isRelease = false;
const int versionMajor = 0;
const int versionMinor = 0;
const int versionPatch = 0;

}  // namespace BuildInfo
