/*
 * Build information - auto-generated by scripts/generate_buildinfo.py
 * Generated: 2025-12-21T23:35:47Z
 */

#include "buildinfo.h"

namespace BuildInfo {

const char* version = "0.0.0-dev";
const char* gitSha = "8b35fb34e4594af783a7b25c9c2bdd6bab77fc65";
const char* gitShortSha = "8b35fb3";
const char* gitBranch = "flyonspeed/platformio";
const char* buildDate = "2025-12-21T23:35:47Z";
const bool isRelease = false;
const int versionMajor = 0;
const int versionMinor = 0;
const int versionPatch = 0;

}  // namespace BuildInfo
